CompostLogo50x50:
		dc.b "c.                                    .:\n"
		dc.b "00l.                                .;kK\n"
		dc.b "xNWXd,                            .:ONWO\n"
		dc.b "':dXWNk:.                       .l0WNOc,\n"
		dc.b "Ok:;l0WW0o'                   'oKWNx:;d0\n"
		dc.b "OWW0l;ckNWXx;.              ,dXWXd::dXWK\n"
		dc.b "'cONWKd:;dKWNOc.          ;xNWKo;:kNWKo,\n"
		dc.b "xo;:xXWNkc;lOWWKo'     .:kNW0l;cONW0l;cx\n"
		dc.b "0WXx:;o0WW0o;:xXWXx;..cOWWOc;l0WNOc;l0WX\n"
		dc.b ",oKWNOl;ckNWXd:;oKWXkONNkc;oKWNk:;oKWNx;\n"
		dc.b "oc;cONWKo;:dKWNkc;cddxd:;dKWXx::dXWXd;:o\n"
		dc.b "KW0o;:xXWXk:;l0WW0o,.';xXWKd;:xXWKo;:kNN\n"
		dc.b ";kNWXx:;o0WW0l;ckNWKxkXW0o;ckNW0l;cONW0c\n"
		dc.b "  ,dKWNOc;ckNWKd:;dkkOkl;lOWWOc;l0WNO:. \n"
		dc.b "    .cOWWKo;:dXWNkc,.',o0WNk:;oKWNx;.   \n"
		dc.b "      .;xXWXx:;l0WWOodKWXx:;dXWXd,      \n"
		dc.b "         'oKWNOl;ck0000d;:xXWKo'        \n"
		dc.b "           .cONWKd;,,,,ckNW0l.          \n"
		dc.b "             .;xXWNxclOWWOc.            \n"
		dc.b "                'o0K0KXk:.              \n"
		dc.b "                  'oxxc.                ", $00

CompostFetch:
		dc.b "\e[31m", "c.                                    .:   root", "\e[97m", "@", "\e[31m", "compostbin\n"
		dc.b "\e[31m", "00l.                                .;kK   ", "\e[97m", "---------------\n"
		dc.b "\e[31m", "xNWXd,                            .:ONWO   OS: ", "\e[97m", "Comp!_OSt 0.01 m68k_020\n"
		dc.b "\e[31m", "':dXWNk:.                       .l0WNOc,   Host: ", "\e[97m", "Computronics MEGASYSTEM 020\n"
		dc.b "\e[31m", "Ok:;l0WW0o'                   'oKWNx:;d0   Kernel: ", "\e[97m", "0.00.1-00-potato\n"
		dc.b "\e[31m", "OWW0l;ckNWXx;.              ,dXWXd::dXWK   Uptime: ", "\e[97m", "NaN\n"
		dc.b "\e[31m", "'cONWKd:;dKWNOc.          ;xNWKo;:kNWKo,   Packages: ", "\e[97m", "0\n"
		dc.b "\e[31m", "xo;:xXWNkc;lOWWKo'     .:kNW0l;cONW0l;cx   Shell: ", "\e[97m", "comp!_OSt shell 0.0.1\n"
		dc.b "\e[31m", "0WXx:;o0WW0o;:xXWXx;..cOWWOc;l0WNOc;l0WX   Resolution: ", "\e[97m", "Nan\n"
		dc.b "\e[31m", ",oKWNOl;ckNWXd:;oKWXkONNkc;oKWNk:;oKWNx;   DE: ", "\e[97m", "tty\n"
		dc.b "\e[31m", "oc;cONWKo;:dKWNkc;cddxd:;dKWXx::dXWXd;:o   WM: ", "\e[97m", "NaN\n"
		dc.b "\e[31m", "KW0o;:xXWXk:;l0WW0o,.';xXWKd;:xXWKo;:kNN   Terminal: ", "\e[97m", "MC68901P\n"
		dc.b "\e[31m", ";kNWXx:;o0WW0l;ckNWKxkXW0o;ckNW0l;cONW0c   CPU: ", "\e[97m", "Motorola MC68020RC16B (1) @ 16.00Mhz\n"  
		dc.b "\e[31m", "  ,dKWNOc;ckNWKd:;dkkOkl;lOWWOc;l0WNO:.    GPU: ", "\e[97m", "Nan\n"
		dc.b "\e[31m", "    .cOWWKo;:dXWNkc,.',o0WNk:;oKWNx;.      Memory: ", "\e[97m", "156KiB / 1024 KiB\n"
		dc.b "\e[31m", "      .;xXWXx:;l0WWOodKWXx:;dXWXd,         \n"
		dc.b "\e[31m", "         'oKWNOl;ck0000d;:xXWKo'           \e[30m██\e[31m██\e[32m██\e[33m██\e[34m██\e[35m██\e[36m██\e[37m██\n"
		dc.b "\e[31m", "           .cONWKd;,,,,ckNW0l.             \e[90m██\e[91m██\e[92m██\e[93m██\e[94m██\e[95m██\e[96m██\e[97m██\n"
		dc.b "\e[31m", "             .;xXWNxclOWWOc.               \n"
		dc.b "\e[31m", "                'o0K0KXk:.                 \n"
		dc.b "\e[31m", "                  'oxxc.                   \n\n"
		dc.b "\e[92m", "root@compostbin", "\e[97m", ":", "\e[94m", "~", "\e[97m", "$ ", $00